### ISSUE TITLE
Network manager constantly calling wlan0

### ISSUE THREAD

**Issue by manbehindthemadness** [goeland86/Kamikaze2#10]
Network manager is calling wlan0 for signal strength, even if it's not present. Journalctl is overflowing with the following:

 <warn>  [1482078765.9286] (wlan0): error getting signal strength: No such device

https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1594814

**Comment by manbehindthemadness** [comment]
Resolution:
http://askubuntu.com/questions/764510/networkmanager757-warn-1461836136-9728-wlan0-error-getting-signal-stre

In file /etc/NetworkManager/NetworkManager.conf under [main] change:

dhcp=dhclient

to

dhcp=internal

**Comment by goeland86** [comment]
If I read this right, in the end we're not just changing the file, you had to recompile a complete network-manager package, right?

**Comment by goeland86** [comment]
I'm marking it as an enhancement as it really isn't a blocker, just a minor annoyance.
