### ISSUE TITLE
prep_ubuntu.sh error

### ISSUE THREAD

**Issue by GearheadRed** [goeland86/Kamikaze2#14]
Issue is on line 18:
`touch /etc/pm/sleep.d/wireless` errors due to

`touch: cannot touch '/etc/pm/sleep.d/wireless': No such file or directory`

problem looks like the `/etc/pm` dir does not exist.

**Comment by GearheadRed** [comment]
Looks like the line below could be added just before the touch command:
`mkdir -p /etc/pm/sleep.d`

That should fix the failure there, it looks like this is meant to disable power management on wireless.

**Comment by GearheadRed** [comment]
Confirmed, fix works as expected.

**Comment by goeland86** [comment]
corrected in the master branch
