### ISSUE TITLE
Request: Public SMB Share for models folder

### ISSUE THREAD

**Issue by manbehindthemadness** [goeland86/Kamikaze2#2]
The addition of a public SMB share aimed at Octoprint's models folder allowing for instant delivery of cgode from any slicer regardless if it supports API integration.

/etc/samba/smb.conf:

[public]
 path = /usr/share/models
 public = yes
 writable = yes
 comment = smb share
 printable = no
 guest ok = yes
 locking = no

**Comment by goeland86** [comment]
While this would be relatively easy and useful, there is the question of how many dependencies SMB (now CIFS) sharing will pull in. I will look at it this weekend.

**Comment by goeland86** [comment]
Ok done. For 30 MB it was an easy setup.
