### ISSUE TITLE
Octoprint wants to install an update at every boot

### ISSUE THREAD

**Issue by goeland86** [goeland86/Kamikaze2#21]
jetguy [reports](https://replicape.slack.com/archives/development/p1484745589004535) that Octoprint wants to install an update on every boot.

This means that somehow the update fails to install for some reason, or that the git permissions on the checkout folder prevent it from downloading the update as expected. Needs to be fixed.

**Comment by jetguy** [comment]
![untitledfail](https://cloud.githubusercontent.com/assets/1012602/22066113/7355e82a-dd59-11e6-866a-dca44b61b37d.png)
![update](https://cloud.githubusercontent.com/assets/1012602/22066114/73572938-dd59-11e6-9a07-0f7ea53ea747.jpg)

**Comment by jetguy** [comment]
It's more an issue of something right at the end with the restart. Also, actually using the restart octoprint works a
![restart failure](https://cloud.githubusercontent.com/assets/1012602/22066219/f632c808-dd59-11e6-923f-54a4b4232b4c.jpg)
s in it reboots, but it throws an error saying it didn't?? Again, it definitely restarts octoprint and I had to capture that message before it through up the reconnect banner on the page.

**Comment by jetguy** [comment]
I finally got a capture of the error details here.
![reboot fail](https://cloud.githubusercontent.com/assets/1012602/22071433/21ca9654-dd6d-11e6-8d6d-1a22c63fa334.jpg)

**Comment by goeland86** [comment]
This was fixed by addressing the installation method of octoprint (i.e. cloning the git isn't the proper way to do so - pip or easy_install is a better way of setting up the initial installation).
