### ISSUE TITLE
Add /sbin/poweroff to sudoers.d

### ISSUE THREAD

**Issue by RaveGun** [goeland86/Kamikaze2#24]
Hello,

Is it a bad thing to add the /sbin/poweroff also to the sudoers.d?
I am mainly using only the "poweroff" command to shutdown any linux machine.
I know it can be done via "shutdown" but I keep forgetting the syntax.

Thank you.

**Comment by goeland86** [comment]
It's a good idea. I keep using the old shutdown command because I forget there's the poweroff alias ;)
