### ISSUE TITLE
Toggle service failing to start

### ISSUE THREAD

**Issue by manbehindthemadness** [goeland86/Kamikaze2#5]
Dec 17 14:30:30 kamikaze systemd[1]: Starting The Redeem/Replicape user interface...
Dec 17 14:30:30 kamikaze systemd[1]: Stopping Getty on tty1...
Dec 17 14:30:30 kamikaze systemd[1]: Stopped Getty on tty1.
Dec 17 14:30:31 kamikaze systemd[1]: Started The Redeem/Replicape user interface.
Dec 17 14:30:34 kamikaze toggle[1411]: /usr/local/lib/python2.7/dist-packages/toggle/Toggle.py:30: PyGIWarning: Mx was imported without specifying a version first. Use gi.require_version('Mx', '2.0') before import to ensure that the right version gets loaded.
Dec 17 14:30:34 kamikaze toggle[1411]:   from gi.repository import Clutter, Mx, Cogl, Mash
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         INFO     Starting Toggle 1.2.1
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         INFO     Using config file /etc/toggle/default.cfg
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         WARNING  Missing config file /etc/toggle/printer.cfg
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         INFO     Using config file /etc/toggle/local.cfg
Dec 17 14:30:35 kamikaze toggle[1411]: (python:1411): Mx-WARNING **: Error loading fallback icon theme
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL Traceback (most recent call last):
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL   File "/usr/local/bin/toggle", line 11, in <module>
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL load_entry_point('Toggle==1.2.1', 'console_scripts', 'toggle')()
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL   File "/usr/local/lib/python2.7/dist-packages/toggle/Toggle.py", line 236, in main
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL t = Toggle()
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL   File "/usr/local/lib/python2.7/dist-packages/toggle/Toggle.py", line 126, in __init__
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL config.splash = Splash(config)
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL   File "/usr/local/lib/python2.7/dist-packages/toggle/Splash.py", line 9, in __init__
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL splash.set_from_file(config.get("System", "splash"))
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL GLib
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL .
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL Error
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL :
Dec 17 14:30:35 kamikaze toggle[1411]: 12-17 14:30 root         CRITICAL gdk-pixbuf-error-quark: Couldn't recognize the image file format for file '/etc/toggle/style/Toggle_splash.png' (3)
Dec 17 14:30:35 kamikaze systemd[1]: toggle.service: Main process exited, code=exited, status=1/FAILURE
Dec 17 14:30:35 kamikaze systemd[1]: Started Getty on tty1.
Dec 17 14:30:36 kamikaze systemd[1]: toggle.service: Unit entered failed state.
Dec 17 14:30:36 kamikaze systemd[1]: toggle.service: Failed with result 'exit-code'.

**Comment by goeland86** [comment]
Thanks, figured it out - missing libs :confounded: they were there on the demo setup we built with Elias...
