### ISSUE TITLE
Enhancement Request: usbreset

### ISSUE THREAD

**Issue by manbehindthemadness** [goeland86/Kamikaze2#6]
Suggest the inclusion of usbreset program to allow for scripted bus resets of 3rd party devices that fail to properly initialize on bootup.

instructions (code below)
cc usbreset.c -o usbreset
chmod +x usbreset
mv usbreset /usr/local/sbin/

--code--

/* usbreset -- send a USB port reset to a USB device */

#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/ioctl.h>

#include <linux/usbdevice_fs.h>

int main(int argc, char **argv)
{
    const char *filename;
    int fd;
    int rc;

    if (argc != 2) {
        fprintf(stderr, "Usage: usbreset device-filename\n");
        return 1;
    }
    filename = argv[1];

    fd = open(filename, O_WRONLY);
    if (fd < 0) {
        perror("Error opening output file");
        return 1;
    }

    printf("Resetting USB device %s\n", filename);
    rc = ioctl(fd, USBDEVFS_RESET, 0);
    if (rc < 0) {
        perror("Error in ioctl");
        return 1;
    }
    printf("Reset successful\n");

    close(fd);
    return 0;
}

**Comment by goeland86** [comment]
Simple enough - added.
