### ISSUE TITLE
Cura Engine

### ISSUE THREAD

**Issue by FuraX49** [goeland86/Kamikaze2#8]
Version 15.04.06 is no longer available on ultimaker repository...

**Comment by goeland86** [comment]
It is, but you need to look at the tags for 15.04.6, not .06. See https://github.com/Ultimaker/CuraEngine/tree/15.04.6

**Comment by FuraX49** [comment]
I just test your script , and i see error...
I verify with  bash 👎 
git checkout tags/15.04.6
error: pathspec 'tags/15.04.6' did not match any file(s) known to git.

**Comment by goeland86** [comment]
Ok checkout again - the reason the checkout failed is because I cloned with depth 1.
I switched to pulling the zip from the github repo instead. The idea is to save as much disk space as possible.

**Comment by FuraX49** [comment]
86 as Vienne ?

**Comment by goeland86** [comment]
try a git pull - you'll see the changes I made to the install_cura method.

**Comment by FuraX49** [comment]
I try to reclone the repository...

**Comment by FuraX49** [comment]
After recloning repository it's works....
Sorry
